### ISSUE TITLE
Feature request: rows defined over multiple lines

### ISSUE THREAD

**Issue by Lucas-C** [RedBug312/markdown-it-multimd-table#2]
Hi.

Do you think it could be possible to add support for multilines tables ?
Like in pandoc: http://pandoc.org/MANUAL.html#tables

Regards

**Comment by redbug312** [comment]
I haven't decided. But I might not add this feature right now because
1. It shows no similarity with pipe_tables of Common Markdown
2. The feature seemed conflicted with the name of this plugin

However, I thought multilines tables is great for the straightforward-ness and headerless feature. 
I would add the feature with an expenrimental flag in future, but not enable it by default.

**Comment by Lucas-C** [comment]
I realize now that "multiline tables" cover more features than I want.
Actually, my precise need here is more limited than full support of pandoc tables. I just provided the link as an example of existing implementation of this feature.
What I really would like exactly is simply rows that can be defined over multiple lines. For example using end-of-the-line backslashes as in pandoc:
```
A | B
-----
1 | 2\
  | 3
```
I'm totally OK with a flag to enable this as an experimental feature though, as it is not standard.

**Comment by Lucas-C** [comment]
But yes, the "headerless" feature would be handy too :)

**Comment by Lucas-C** [comment]
I'd be willing to submit a PR.
Could you just tell me if you approve the idea of a flag-enabled feature to support end-of-the-line backslashes ?
