### ISSUE TITLE
Feature request: Support header below table or even (multiple) headers at arbitrairy positions

### ISSUE THREAD

**Issue by Meteor0id** [RedBug312/markdown-it-multimd-table#26]
Title says enough: I am floating the idea to support having the header either above, or below, or both above and below the table.
In fact, maybe the header could even be repeated within the table. This is especially useful in very long tables where anyone viewing would otherwise need to scroll up rather far.

**Comment by redbug312** [comment]
I cannot add this feature since this introduces too much overhead to current implementation, while the usefulness is doubted.

From another aspect, MultiMarkdown [requirement 2](https://fletcher.github.io/MultiMarkdown-5/tables.html) suggests a separator dividing headers and contents. Enabling headers at arbitary position surely needs new syntax, but I haven't seen relevant discussions of that in other Markdown derivatives.

I would reconsider this if there are discussions of similar features. Thank you for the suggestion still!

**Comment by Meteor0id** [comment]
I think headers at the bottom and at arbitrary potions can end up being very useful, as the headers can have different content at different rows. It allows for tables with more complex information in them. Or like in the first post, you can repeat the same header just to make the table easier to read. In the case of repeating the previous header, it might be best to use a symbol to indicate 'same as previous' rather than having to modify the header at different rows. This also saves characters / byte size.

**Comment by redbug312** [comment]
Thanks for these interesting ideas. But this plugin aims to follow MultiMarkdown spec as tight as possible. I'm declined to invent new syntax here because I don't want this becoming *another one* Markdown standard. The options are created since the features (1) have been proposed in other derivatives and (2) are easy to be integrated into. Even with that, they're all disabled by default.

I would suggest these feature requests to be directly sent to MultiMarkdown. I'm willing to add any feature from upstream standard in no case.
