### ISSUE TITLE
Featature request: Define relative and/or absolute comumn width

### ISSUE THREAD

**Issue by Meteor0id** [RedBug312/markdown-it-multimd-table#27]
It would be great if we can define using markdown syntax with columns we prefer to be wide, and which may be narrow.

The number of dashes could indicate relative column width:

`
name of feature | has been implemented | in version | available on desktop | max limit
-----|-|–|-|–
`
`
Sharing attachments with preview image | :white_check_mark: | 12.1.0 | :x: | 25 MiB
`

I know this would require styling such as normally done in CSS, because defining with can't be done with HTML, but mind you markdown does already support some styling when doing things like aligning content to the right or center of a cell, so this is not unprecedented.

**Comment by redbug312** [comment]
Widths seemed less discussed, but I also think it interesting because evenly-distributed columns suggest the similarity between them. As the author of pandoc [has mentioned](https://github.com/jgm/pandoc/issues/2486#issuecomment-151915797), many users uses extra hyphen signs just to format. Doing tricks on hyphens would be annoying.

Equal signs seems have a chance, for it being [legal in MultiMarkdown](https://fletcher.github.io/MultiMarkdown-6/syntax/tables.html) while [illegal in GFM](https://github.github.com/gfm/#tables-extension-). That is, hyphens for auto and equals for widths.

However, I'd go for absolute column widths with units in `em`. The options cannot be applied per-table, so default `width: auto` must be supported. Relative widths leave no space for auto-width columns; Units in percentages hardly satisfy two-column-wide (50%) and three-column-wide (33%).

**Comment by redbug312** [comment]
In this case, the expected behavior (units in `em`) will be:

```markdown
name of feature | has been implemented | in version | available on desktop | max limit
-----|:========:|:========:|:========:|:========:
Sharing attachments with preview image | :white_check_mark: | 12.1.0 | :x: | 25 MiB
 
name of feature | has been implemented | in version | available on desktop | max limit
-----|:--------:|:--------:|:--------:|:--------:
Sharing attachments with preview image | :white_check_mark: | 12.1.0 | :x: | 25 MiB
```

![image](https://user-images.githubusercontent.com/11537681/81241615-53b50b00-903d-11ea-926b-04cb479a6dbc.png)

**Comment by Meteor0id** [comment]
Can there be more than just two kinds of width?

**Comment by redbug312** [comment]
If needed, I would try implementing absolute widths first, and see if I can came up with reasonable strategy to integrate relative widths and default auto widths.
