### ISSUE TITLE
Space sensitivity v3 versus v4

### ISSUE THREAD

**Issue by dk-teknologisk-mnm** [RedBug312/markdown-it-multimd-table#36]
Between version 3 and 4 I noticed a change in sensitivity for inserting spaces. If a space is placed in the beginning of a new line, before the first pipe of the table, the space seems to be parsed as cell content.

```
| Column 1 | Column 2 | Column 3 |
| :------- | :------- | :------- |
 | Row 1   | Content  | Content  |
 | Row 2   | Content  | Content  |
```

So in v3 the above markdown would be parsed as this:
![image](https://user-images.githubusercontent.com/75021942/115016672-ae91ec00-9eb5-11eb-83ff-ded7343f4339.png)

And in v4 it gives this:
![image](https://user-images.githubusercontent.com/75021942/115016499-65419c80-9eb5-11eb-9997-e72fdab6e981.png)

Is this a regression bug or a feature?

**Comment by redbug312** [comment]
Thanks for the issue. This is kind of a feature, to keep consistent with the multi-line option.
(though this is against the behavior of markdown-it)
So that users need not add leading pipes when 1st cell of the continuing line is empty, as

```
column 1 | column 2
---------|---------
row 1    | content \
         | and continue
```

be like

<table>
<thead>
<tr>
<th>column 1</th>
<th>column 2</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<p>row 1</p>
</td>
<td>
<p>content
and continue</p>
</td>
</tr>
</tbody>
</table>
