### ISSUE TITLE
colspan not rendered properly

### ISSUE THREAD

**Issue by carlo161** [RedBug312/markdown-it-multimd-table#67]
Hello,
I am trying to design a specific table in Joplin but I could not find out how to do it.
With the following:
```
| :---: | :---: | :---: | :---: |
| a ||| b |
| c || d  | ^^ |
| e | f || ^^ |
| ^^ | g || ^^ |
| ^^ | h || ^^ |
| ^^ |  || ^^ |
``` 
I expect the table rendered in 4 columns and the "c" cell that spans 2 columns. But I obtain the whole table in 3 columns and the "c", "d", "e" and "f" cells with the same colspan.

![image](https://github.com/redbug312/markdown-it-multimd-table/assets/30337724/83aca3f3-0ae0-47a5-9d38-27c9d8ff98e2)

Am I doing something wrong?

**Comment by nxjniexiao** [comment]
I had a similar problem. But I don't think it's a bug of markdown-it-multimd-table, because the colspan attribute of `<td>` is correct.
If we add a row, the table will display correctly.
```
| :---: | :---: | :---: | :---: |
| a | a | a | a |
| a ||| b |
| c || d  | ^^ |
| e | f || ^^ |
| ^^ | g || ^^ |
| ^^ | h || ^^ |
| ^^ |  || ^^ |
```

Rendering result:

<table>
<tbody>
<tr>
<td style="text-align:center">a</td>
<td style="text-align:center">a</td>
<td style="text-align:center">a</td>
<td style="text-align:center">a</td>
</tr>
<tr>
<td style="text-align:center" colspan="3">a</td>
<td style="text-align:center" rowspan="6">b</td>
</tr>
<tr>
<td style="text-align:center" colspan="2">c</td>
<td style="text-align:center">d</td>
</tr>
<tr>
<td style="text-align:center" rowspan="4">e</td>
<td style="text-align:center" colspan="2">f</td>
</tr>
<tr>
<td style="text-align:center" colspan="2">g</td>
</tr>
<tr>
<td style="text-align:center" colspan="2">h</td>
</tr>
<tr>
<td style="text-align:center" colspan="2"></td>
</tr>
</tbody>
</table>

**Comment by carlo161** [comment]
Thanks, I could solve by adding a row below or also by adding the header row.
Probably to be rendered properly at least one row should have really 4 columns.
